package amz

import (
	"fmt"
	"net/url"
	"sort"
	"strings"
)

// Reading a page as a report rather than as a record.
//
// Every parser in this package already produces an Envelope saying which fields
// it filled, where each one came from, which ones it missed and which named
// regions nothing read. That envelope is the interesting part twice over: it is
// what a caller checks before trusting a record, and it is what tells us the
// site changed under us. What was missing was a way to ask for it on its own,
// for a page on disk, without going through a fetch and a record type.
//
// That is what this file is. It runs the real parser, not a second one written
// for reporting, which is the whole point: a report generated by a different
// code path would be a report about that code path.

// Extraction is one page read, described.
type Extraction struct {
	// URL is the page this describes, and Op is the surface it belongs to,
	// "product" or "author" rather than the family both share.
	URL string `json:"url"`
	Op  string `json:"op"`
	// Family is the anchor vocabulary the page was read under.
	Family Family `json:"family"`
	// Bytes is the size of the body that was read, which belongs here because a
	// page that got much smaller is usually a page that stopped being served
	// rather than a page that lost fields.
	Bytes int `json:"bytes"`
	// Set counts the fields that came back with a value, Missed counts the
	// declared fields that did not, and Unread counts the regions Amazon named
	// that no field reads. The three of them are the drift signal: Set falling
	// or Unread rising means the page moved.
	Set    int `json:"set"`
	Missed int `json:"missed"`
	Unread int `json:"unread"`
	// Envelope is the full provenance, for a caller that wants the detail rather
	// than the counts.
	Envelope Envelope `json:"envelope,omitzero"`
	// Records counts the repeated records on a page that carries them, the cards
	// on a search page or the tiles on a chart. It is zero on a detail page,
	// which has one record and does not repeat it.
	Records int `json:"records,omitempty"`
}

// Fields lists the fields that came back with a value, in name order.
func (x Extraction) Fields() []string {
	out := make([]string, 0, len(x.Envelope.Via))
	for f := range x.Envelope.Via {
		out = append(out, f)
	}
	sort.Strings(out)
	return out
}

// ExtractBody reads a page that has already been fetched and reports what the
// parser made of it.
//
// The surface is taken from the URL rather than from the caller, because the URL
// is what decides which parser runs in production and a report that let the
// caller pick a different one would be reporting on a page nobody will read that
// way. A URL this package has no parser for is an error rather than a guess.
func (c *Client) ExtractBody(rawURL string, body []byte) (Extraction, error) {
	op := OpFor(rawURL)
	if op == nil {
		return Extraction{}, fmt.Errorf("%w: no surface matches %q", ErrNotFound, rawURL)
	}
	x := Extraction{URL: rawURL, Op: op.Name, Family: FamilyFor(rawURL), Bytes: len(body)}
	u, err := url.Parse(rawURL)
	if err != nil {
		return Extraction{}, err
	}

	switch op.Name {
	case "product", "offers", "reviews", "qa":
		asin, _ := c.ResolveProductURL(rawURL)
		p, err := c.parseProduct(asin, rawURL, body)
		if err != nil {
			return x, err
		}
		x.Envelope = p.Envelope
	case "search":
		q := u.Query().Get("k")
		page := atoiDefault(u.Query().Get("page"), 1)
		s, err := c.parseSearchPage(q, rawURL, page, body)
		if err != nil {
			return x, err
		}
		x.Envelope, x.Records = s.Envelope, len(s.Cards)
	case "bestsellers", "new-releases", "movers", "most-wished-for", "most-gifted":
		p, err := c.parseChartPage(op.Name, "", chartNode(u), rawURL, 1, body)
		if err != nil {
			return x, err
		}
		x.Envelope, x.Records = p.Envelope, len(p.Entries)
	case "category", "deals":
		p, err := c.parseBrowsePage(chartNode(u), rawURL, body)
		if err != nil {
			return x, err
		}
		x.Envelope, x.Records = p.Envelope, p.Items
	case "brand":
		b, err := parseBrandPage(brandSlug(rawURL), rawURL, body)
		if err != nil {
			return x, err
		}
		x.Envelope, x.Records = b.Envelope, len(b.Nav)
	case "author":
		a, err := c.parseAuthorPage(authorSlug(rawURL), rawURL, body)
		if err != nil {
			return x, err
		}
		x.Envelope, x.Records = a.Envelope, len(a.Books)
	case "seller":
		s, err := c.parseSellerPage(u.Query().Get("seller"), rawURL, body)
		if err != nil {
			return x, err
		}
		x.Envelope, x.Records = s.Envelope, len(s.Reviews)
	default:
		return x, fmt.Errorf("%w: surface %q has no parser", ErrNotFound, op.Name)
	}

	x.Set = len(x.Envelope.Via)
	x.Missed = len(x.Envelope.Missed)
	x.Unread = len(x.Envelope.Unread)
	// The agent map is a page description rather than a reading of one, it is
	// the largest thing in the envelope, and it is already available under its
	// own command. Carrying it here would make every line of a ledger a
	// kilobyte of JSON.
	x.Envelope.AgentMap = nil
	return x, nil
}

// chartNode is the browse node in a chart or category URL.
//
// Both spell it as the last path segment after the category name, and both also
// accept the node in a query parameter, so this reads the query first and falls
// back to the path.
func chartNode(u *url.URL) string {
	if n := u.Query().Get("node"); n != "" {
		return n
	}
	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	last := parts[len(parts)-1]
	if isDigits(last) {
		return last
	}
	return ""
}

func isDigits(s string) bool {
	if s == "" {
		return false
	}
	for i := range len(s) {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

func atoiDefault(s string, def int) int {
	n := 0
	if !isDigits(s) {
		return def
	}
	for i := range len(s) {
		n = n*10 + int(s[i]-'0')
	}
	return n
}
